<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Consultoria de Emagrecimento</title>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      margin: 0;
      padding: 0;
      background-color: #fff;
      color: #333;
      line-height: 1.6;
    }
    header {
      background-color: #d62d2d;
      color: white;
      padding: 40px 20px;
      text-align: center;
    }
    header h1 {
      margin: 0;
      font-size: 32px;
    }
    header p {
      font-size: 20px;
      margin-top: 10px;
    }
    .container {
      max-width: 800px;
      margin: auto;
      padding: 20px;
    }
    h2, h3 {
      color: #d62d2d;
    }
    .highlight {
      text-align: center;
      font-size: 20px;
      margin: 30px 0;
    }
    ul {
      padding-left: 20px;
      font-size: 18px;
    }
    .button {
      display: inline-block;
      background-color: #25d366;
      color: white;
      padding: 15px 30px;
      border-radius: 8px;
      text-decoration: none;
      font-size: 18px;
      margin-top: 20px;
    }
    .cta {
      text-align: center;
      margin: 50px 0;
    }
    footer {
      background-color: #f4f4f4;
      text-align: center;
      padding: 20px;
      font-size: 14px;
      color: #777;
    }
  </style>
</head>
<body>
  <header>
    <h1>TRANSFORME SEU CORPO</h1>
    <p>Resultados reais em até 2 semanas</p>
  </header>

  <div class="container">
    <h2>Chega de Frustração!</h2>
    <p style="text-align:center;">Com um plano alimentar feito pra você e treino personalizado.</p>

    <div class="highlight">
      <strong>SAÚDE • LEVEZA • AUTOESTIMA</strong>
      <p>Você irá conquistar:</p>
    </div>

    <h3>Nutricionista</h3>
    <p><strong>Marcela Cunha</strong> — Pós-graduada em Nutrição Funcional, há 7 anos transformando vidas.<br>
    Ensino você a emagrecer com equilíbrio, sem dietas restritivas.<br>
    O foco é transformar o corpo com leveza e resgatar sua autoestima.</p>

    <h3>Personal Trainer</h3>
    <p><strong>Giselle Macena</strong> — Especialista em grupos especiais, com foco em emagrecimento de verdade.<br>
    Cada treino respeita seu ritmo e acelera seus resultados.</p>

    <h2>O que está incluso na consultoria?</h2>
    <ul>
      <li><strong>Consulta por vídeo chamada</strong></li>
      <li><strong>Avaliação por fotos</strong> para adequar o plano à sua realidade</li>
      <li><strong>Plano alimentar estratégico</strong> e <strong>treino adaptado</strong> à sua rotina</li>
      <li><strong>Suporte diário</strong> via WhatsApp ou Direct</li>
    </ul>

    <div class="cta">
      <h2>Consultoria Online</h2>
      <a href="http://wa.me/83996197990" class="button">Fale conosco no WhatsApp</a>
    </div>

    <div class="cta">
      <h3>Pronta(o) para se sentir mais leve, saudável e confiante?</h3>
      <a href="http://wa.me/83996197990" class="button">Comece agora</a>
    </div>
  </div>

  <footer>
    &copy; 2025 Consultoria Marcela & Giselle. Todos os direitos reservados.
  </footer>
</body>
</html>
